### ISSUE TITLE
第四章中练习部分翻译意思不明确。

### ISSUE THREAD

**Issue by Humyang** [llh911001/mostly-adequate-guide-chinese#16]
// 1. 重构使之成为一个 curry 函数
//原文： Refactor to remove all arguments by partially applying the function.
“重构使之成为一个 curry 函数” 对于初学者来说太难理解，而原文较清晰 “通过重构函数部分移除所有参数”。

//1a. 使用 `map` 创建一个新函数，使之能够操作字符串数组
//原文：Use map to make a new words fn that works on an array of strings.
原文说使用 map 创建一个新的 words 函数，我看了答案才明白原来与第一题有关联，才明白为什么题目编号是 1a。

**Comment by llh911001** [comment]
多谢指出，已经改正😁
