### ISSUE TITLE
第一章 some celestial compass for when the waters get rough

### ISSUE THREAD

**Issue by monkindey** [llh911001/mostly-adequate-guide-chinese#21]
原文翻译
> 就像《激战》游戏里当水变成石头的时候你需要天国罗盘来指引

我对这句话的理解是:
就像当水变得**很急，洶涌**的时候你需要**天文罗盘**来指引。

总是想象不出水变成石头。

您觉得呢？

**Comment by llh911001** [comment]
您说得有道理。
当时搜索 celestial compass，第一个出来的是 Guild Wars 这款游戏里的道具，然而我对这款游戏也不了解，就想当然地认为游戏中有水变石头的剧情，因此导致了这个贻笑大方的翻译。
谢谢指正！
