### ISSUE TITLE
关于第十一章翻译

### ISSUE THREAD

**Issue by creamidea** [llh911001/mostly-adequate-guide-chinese#36]
Hi, llh911001

感谢你之前的翻译，让我学习到了许多。最近翻看原作者的文章，发现已经有 11 章和 12 章的内容。不知道大佬是否有精力继续翻译。

期待。 😆

**Comment by llh911001** [comment]
感谢提醒！

之前没注意到，原来作者已经更新了两章内容。放心，近期我会抽空翻译出来的 😀

**Comment by creamidea** [comment]
谢谢大佬

**Comment by nangonghuang** [comment]
之前的内容也有变化，代码的写法都从es5更新到es6的箭头函数了

**Comment by Expelliarmus923** [comment]
希望能翻译下最新版本，变化了很多内容。

**Comment by liuliangsir** [comment]
为啥大家不尝试着自己也去参与翻译呢？看别人翻译的文章跟自己去翻译别人的文章，效果是千差万别的

**Comment by llh911001** [comment]
抱歉了，最近实在工作上有些忙，没时间更新。多谢大家关注！

@liuliangsir 同学说得很中肯哈，读完原文再自己尝试翻译，会有更深的理解呢。

顺便这里也广告下，大家有兴趣参与翻译、更新的，可以随时提 PR，我看到了会 review、合并的 😀 

再次感谢！
